= vocab
By Harsh Kapadia
v1
:favicon:   ./src/static/img/icon.svg
:toc:		left
:icons:		font
:docinfo:   shared

== Abstract

This web site contains some English vocabulary for https://www.ets.org/gre/[GRE^].

== Preface

A good English vocabulary is immensely important for the GRE examination. Learning and keeping track of words is difficult, so the author, https://www.linkedin.com/in/harshgkapadia/[Harsh Kapadia^], is using this web site as a track of the words that he is learning.

This web site is a work in progress and is constantly updated! The web site source code can be found on https://github.com/HarshKapadia2/vocab[GitHub^]. Do not hesitate to raise an https://github.com/HarshKapadia2/vocab/issues[issue^] if there is any mistake/typo in the web site. Inputs and suggestions are appreciated and most welcome!

The author, Harsh Kapadia, can be contacted via https://twitter.com/harshgkapadia[Twitter^], https://www.linkedin.com/in/harshgkapadia/[LinkedIn^] or e-mail (harshgkapadia@gmail.com).

== A

include::./refs/a.adoc[]

== B

include::./refs/b.adoc[]

== C

include::./refs/c.adoc[]

== D

include::./refs/d.adoc[]

== E

include::./refs/e.adoc[]

== F

include::./refs/f.adoc[]

== G

include::./refs/g.adoc[]

== I

include::./refs/i.adoc[]

== J

include::./refs/j.adoc[]

== K

include::./refs/k.adoc[]

== L

include::./refs/l.adoc[]

== M

include::./refs/m.adoc[]

== O

include::./refs/o.adoc[]

== P

include::./refs/p.adoc[]

== R

include::./refs/r.adoc[]

== S

include::./refs/s.adoc[]

== T

include::./refs/t.adoc[]

== U

include::./refs/u.adoc[]

== V

include::./refs/v.adoc[]

== W

include::./refs/w.adoc[]

'''

== Sources

* https://dictionary.cambridge.org/[The Cambridge Dictionary^]
* https://www.merriam-webster.com/[The Merriam-Webster Dictionary^]
* https://www.amazon.com/30-Days-More-Powerful-Vocabulary/dp/067174349X[30 Days to a More Powerful Vocabulary^]

'''

[quote, Selena Gomez]
Kindness always wins.

++++
	<div class="pwa-install-div hidden">
		<div id="pwa-install-text">Ready for offline use!</div>
		<button id="pwa-install-btn">Install</button>
		<button id="pwa-install-dismiss">
			<img src="static/img/clear_cross.svg" alt="X">
		</button>
	</div>
++++
